FiiApp/FiiApp.Presentation/FiiApp.Dashboard/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using FiiApp.Dashboard.Models;
using FiiApp.Services.Helpers;
using FiiApp.Services.StudentServices;
using FiiApp.Services.UserServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Tokens;

namespace FiiApp.Dashboard.Controllers
{
  [AllowAnonymous]
  [Route("api/[controller]")]
  [ApiController]
  public class AuthController : ControllerBase
  {
    private readonly IUserService userService;
    private readonly IStudentService studentService;
    private readonly IConfiguration configuration;
    private readonly IMapper mapper;

    public AuthController(IUserService userService, IStudentService studentService, IConfiguration configuration, IMapper mapper)
    {
      this.userService = userService;
      this.studentService = studentService;
      this.configuration = configuration;
      this.mapper = mapper;
    }

    [HttpPost("GetToken")]
    public IActionResult GetToken(string username, string password)
    {
      var user = userService.AuthenticateUser(username, password);

      if (user is null)
        return BadRequest(new { message = "The username or password is incorrect" });
      
      var securityKey = configuration["JWTDetails:SecurityKey"];
      var symmetricSecurityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(securityKey));
      var signingCredentials = new SigningCredentials(symmetricSecurityKey, SecurityAlgorithms.HmacSha256Signature);

      var claims = new List<Claim>();
      claims.Add(new Claim(ClaimTypes.Role, user.Role));
      claims.Add(new Claim("UserId", user.Id.ToString()));

      if (user.Role == UserRoles.Student)
      {
        var student = studentService.GetStudentByUserId(user.Id);
        claims.Add(new Claim("UserFullName", $"{student.FirstName} {student.LastName}"));
        claims.Add(new Claim("UserEmail", student.Email));
      }

      //create token
      var jwttoken = new JwtSecurityToken(
              issuer: configuration["JWTDetails:Issuer"],
              audience: configuration["JWTDetails:Audience"],
              expires: DateTime.Now.AddHours(1),
              signingCredentials: signingCredentials,
              claims: claims
          );
      var token = new JwtSecurityTokenHandler().WriteToken(jwttoken);

      var loggedUser = mapper.Map<UserModel>(user);
      loggedUser.Token = token;
      return Ok(loggedUser);
    }

    [HttpPost("RegisterNewUser")]
    public IActionResult RegisterNewUser(string registrationNumber, string email, string password)
    {
      // verify if student with credentials exists in database
      var studentExists = userService.VerifyIfStudentExists(registrationNumber, email);
      if (!studentExists)
        return BadRequest(new { message = "The student with the entered registration number and webmail address does not exist" });

      // verify if student has associated an user id
      var userExists = userService.VerifyIfStudentHasAccount(registrationNumber, email);
      if (userExists)
        return BadRequest(new { message = "The student with the entered registration number and webmail address already has an account" });

      // register new user
      var username = userService.RegisterNewUser(registrationNumber, email, password);
      return GetToken(username, password);
    }
  }
}

FiiApp/FiiApp.Presentation/FiiApp.Dashboard/Controllers/FacultyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FiiApp.Dashboard.Helpers;
using FiiApp.Dashboard.Models;
using FiiApp.Services.FacultyServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FiiApp.Dashboard.Controllers
{
  [Authorize]
  [Route("api/[controller]")]
  [ApiController]
  public class FacultyController : ControllerBase
  {
    private readonly IFacultyService facultyService;
    private readonly IMapper mapper;

    public FacultyController(IFacultyService facultyService, IMapper mapper)
    {
      this.facultyService = facultyService;
      this.mapper = mapper;
    }

    [HttpGet("StudentFinalGrades")]
    public IActionResult GetStudentFinalGrades(int semester)
    {
      var userId = 0;
      if (Int32.TryParse(HeaderValueReader.GetUserId(Request), out userId))
      {
        var grades = facultyService.GetStudentFinalGrades(userId, semester);
        return Ok(mapper.Map<IEnumerable<FinalGradeModel>>(grades));
      }
      return BadRequest(new { message = "Something went wrong when trying to get student grades" });
    }

    [HttpGet("StudentClassAndEnrollmentYear")]
    public IActionResult GetStudentClassAndEnrollmentYear()
    {
      var userId = 0;
      if (Int32.TryParse(HeaderValueReader.GetUserId(Request), out userId))
      {
        var year = facultyService.GetStudentEnrollmentYear(userId);
        var currentClass = facultyService.GetStudentClass(userId);
        return Ok(new { academicYear = year, studentClass = currentClass });
      }
      return BadRequest(new { message = "Something went wrong when trying to get student class and enrollment year" });
    }

    [HttpGet("StudentGradesForCourse")]
    public IActionResult GetStudentGradesForCourse(int courseId)
    {
      var userId = 0;
      if (Int32.TryParse(HeaderValueReader.GetUserId(Request), out userId))
      {
        var grades = facultyService.GetStudentGradesForCourse(userId, courseId);
        return Ok(mapper.Map<IEnumerable<GradeModel>>(grades));
      }
      return BadRequest(new { message = "Something went wrong when trying to get student grades for course" });
    }

    [HttpGet("StudentMeansForGrades")]
    public IActionResult GetStudentGradesMeans()
    {
      var userId = 0;
      if (Int32.TryParse(HeaderValueReader.GetUserId(Request), out userId))
      {
        var means = facultyService.CalculateStudentMeans(userId);
        return Ok(mapper.Map<IEnumerable<GradesMeanModel>>(means));
      }
      return BadRequest(new { message = "Something went wrong when trying to get student grades means" });
    }

    [HttpGet("Teachers")]
    public IActionResult GetTeachers()
    {
      var teachers = facultyService.GetTeachers();
      return Ok(mapper.Map<IEnumerable<TeacherModel>>(teachers));
    }

    [HttpGet("StudentsGradesPerSemester")]
    public JsonResult GetStudentsGradesPerSemester()
    {
      var averages = facultyService.GetStudentsGradesPerSemester();
      return new JsonResult(averages);
    }

    [HttpGet("NumberOfEachGrade")]
    public JsonResult GetNumberOfEachGrade()
    {
      var numberOfGrades = facultyService.GetNumberOfEachGrade();
      return new JsonResult(numberOfGrades);
    }

    [HttpGet("CurrentUserGradesPerSemester")]
    public JsonResult GetCurrentUserGradesPerSemester()
    {
      var userId = 0;
      if (Int32.TryParse(HeaderValueReader.GetUserId(Request), out userId))
      {
        var grades = facultyService.GetCurrentUserGradesPerSemester(userId);
        return new JsonResult(grades);
      }
      return null ;
    }

  }
}

FiiApp/FiiApp.Presentation/FiiApp.Dashboard/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FiiApp.Dashboard.Helpers;
using FiiApp.Dashboard.Models;
using FiiApp.Services.DTOs;
using FiiApp.Services.SendGridEmailServices;
using FiiApp.Services.UserServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FiiApp.Dashboard.Controllers
{
  [Authorize()]
  [Route("api/[controller]")]
    [ApiController]
    public class UserController : ControllerBase
    {
    private readonly IUserService userService;
    private readonly IEmailService emailService;
    private readonly IMapper mapper;

    public UserController(IUserService userService, IEmailService emailService, IMapper mapper)
    {
      this.userService = userService;
      this.emailService = emailService;
      this.mapper = mapper;
    }


    [HttpPost("SendEmail")]
    public IActionResult SendEmail([FromBody]FiiAppEmailModel emailModel)
    {
      emailModel.FromEmail = HeaderValueReader.GetUserEmail(Request);
      emailModel.FromName = HeaderValueReader.GetUserFullName(Request);
      try
      {
        var emailDto = mapper.Map<FiiAppEmailDto>(emailModel);
        emailService.SendEmailMessage(emailDto);
        return Ok(new { message = "Message sent."});
      }
      catch (Exception ex)
      {
        Trace.WriteLine("There is a problem at email sending.\n" + ex.Message);
        return BadRequest(new { message = "There is a problem at email sending." });
      }
    }

    [HttpGet("GetUserInfo")]
    public IActionResult GetUserInfo()
    {
      var userId = 0 ;
      if(Int32.TryParse(HeaderValueReader.GetUserId(Request), out userId))
      {
        var userInfo = userService.GetStudentInformation(userId);
        return Ok(mapper.Map<StudentModel>(userInfo));
      }
      return BadRequest(new { message = "Something went wrong when trying to get user info" });
    }
  }
}

FiiApp/FiiApp.Presentation/FiiApp.Dashboard/Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FiiApp.Dashboard.Helpers;
using FiiApp.Services.FacultyServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FiiApp.Dashboard.Controllers
{
  [Authorize(Roles = "Student")]
  [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {

    private readonly IFacultyService facultyService;

    public ValuesController(IFacultyService facultyService)
    {
      this.facultyService = facultyService;
    }

    [HttpGet]
    public string GetTestValues()
    {
      var xx = HeaderValueReader.GetUserId(Request);
      var cc = HeaderValueReader.GetUserRole(Request);
      var text = facultyService.Ceva();
      return text + "          Ana are mere" + xx + cc;
    }





        //// GET: api/Values
        //[HttpGet]
        //public IEnumerable<string> Get()
        //{
        //    return new string[] { "value1", "value2" };
        //}

        //// GET: api/Values/5
        //[HttpGet("{id}", Name = "Get")]
        //public string Get(int id)
        //{
        //    return "value";
        //}

        //// POST: api/Values
        //[HttpPost]
        //public void Post([FromBody] string value)
        //{
        //}

        //// PUT: api/Values/5
        //[HttpPut("{id}")]
        //public void Put(int id, [FromBody] string value)
        //{
        //}

        //// DELETE: api/ApiWithActions/5
        //[HttpDelete("{id}")]
        //public void Delete(int id)
        //{
        //}
    }
}

FiiApp/FiiApp.Presentation/FiiApp.Dashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="img/facultylogo.png">
    <title>Paula Licenta</title>

    <!--  Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">
    <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">

    <base href="~/" />
</head>
<body>
  <input type="hidden" id="axiosUrls"
         data-loginTokenUrl="@Url.Action("GetToken","Auth")"
         data-registerUrl="@Url.Action("RegisterNewUser","Auth")"
         data-sendEmailUrl="@Url.Action("SendEmail","User")"
         data-userInfoUrl="@Url.Action("GetUserInfo","User")"
         data-studentGradesUrl="@Url.Action("GetStudentGradesForCourse","Faculty")"
         data-studentFinalGradesUrl="@Url.Action("GetStudentFinalGrades","Faculty")"
         data-studentGradesMeansUrl="@Url.Action("GetStudentGradesMeans","Faculty")"
         data-studentClassAndEnrollmentYearUrl="@Url.Action("GetStudentClassAndEnrollmentYear","Faculty")"
         data-teachersUrl="@Url.Action("GetTeachers","Faculty")"
         data-gradesPerSemesterUrl="@Url.Action("GetStudentsGradesPerSemester","Faculty")"
         data-currentUserGradesPerSemesterUrl="@Url.Action("GetCurrentUserGradesPerSemester","Faculty")"
         data-numberOfGradesUrl="@Url.Action("GetNumberOfEachGrade","Faculty")"
         data-testLoginUrl="@Url.Action("GetTestValues","Values")" 
         data-ECTSPredictionUrl="@Url.Action("GetECTSPredictionGrade","MLAndStatistics")"
         data-PFPredictionUrl="@Url.Action("GetPFPredictionGrade","MLAndStatistics")"
         data-mathStatisticsUrl="@Url.Action("GetMathStatisticsData","MLAndStatistics")"
         data-attendanceStatisticsUrl="@Url.Action("GetAttendanceStatistics","MLAndStatistics")"
         data-genderStatisticsUrl="@Url.Action("GetGenderStatistics","MLAndStatistics")"
         data-finalScoreStatisticsByYearUrl="@Url.Action("GetFinalScoreStatisticsByYear","MLAndStatistics")"
         data-finalScoreStatisticsByClassUrl="@Url.Action("GetFinalScoreStatisticsByClass","MLAndStatistics")"
         data-finalScoreStatisticsByGenderUrl="@Url.Action("GetFinalScoreStatisticsByGender","MLAndStatistics")"
         data-seminarActivityStatisticsUrl="@Url.Action("GetSeminarActivityStatistics","MLAndStatistics")"
         data-passedStudentsStatisticsUrl="@Url.Action("GetNumberOfPassedStudents","MLAndStatistics")"
         />

  @RenderBody()
  <script src="~/dist/main.js" asp-append-version="true"></script>
</body>
</html>